config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "stories#index"

  get "hide_details" => "stories#hide_details"
  get "show_details" => "stories#show_details"
  get "show_edit" => "stories#show_edit"
  get "hide_edit" => "stories#hide_edit"
  get "toggle_publicity" => "stories#toggle_publicity"
  # get "show_add_scene" => "scenes#show_add_scene"
  get "hide_edit_scene" => "scenes#hide_edit_scene"
  get "toggle_endgame" => "scenes#toggle_endgame"
  get "set_start_scene" => "stories#set_start_scene"
  get "make_choice" => "stories#make_choice"

  resources :accounts do
    resources :stories
  end

  resources :stories do
    resources :scenes
  end

  resources :scenes do
    resources :choices
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user, foreign_key: :user_id, optional: true
  has_many :stories, dependent: :destroy

  def public_stories
    self.stories.where("public = true").find_all{ |s| s.is_valid? }
  end

  def private_stories
    self.stories.where("public = false").find_all{ |s| s.is_valid? }
  end

  def invalid_stories
    self.stories.find_all{ |s| !s.is_valid? }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :scene, foreign_key: :scene_id, optional: true
  validates :text, :dest_scene_id, presence: true
end

app/models/scene.rb
class Scene < ApplicationRecord
  belongs_to :story, foreign_key: :story_id, optional: true
  has_many :choices, dependent: :destroy
  validates :title, :text, presence: true

  def get_desc (length)
    if self.text.length <= length
      self.text
    else
      self.text.slice(0,length-1).chomp(".").concat('...')
    end
  end

  def get_choices (count)
    if self.choices.count <= count
      self.choices
    else
      self.choices.limit(count)
    end
  end

  def toggle_endgame
    self.update_attribute :endgame, !self.endgame
  end

  def self.title_by_id(id)
    self.find(id).title
  end
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :account, foreign_key: :account_id, optional: true
  has_many :scenes, dependent: :destroy
  validates :title, :description, presence: true

  scope :most_recent_public, -> count {
    where("public = true").order(created_at: :desc).limit(count).find_all {|s| s.is_valid?}
  }

  after_create :add_color

  def add_color
    self.update_attribute :color, "rgb(#{rand(255)}, #{rand(255)}, #{rand(255)})"
  end

  def self.all_public
    self.where("public = true").find_all {|s| s.is_valid?}
  end

  def short_desc
    if self.description.length > 140
      self.description.slice(0,140).chomp(".").concat('...')
    else
      self.description
    end
  end

  def select_options
    self.scenes.map do |scene|
      [scene.title, scene.id]
    end
  end

  def toggle_publicity
    self.update_attribute :public, !self.public
  end

  def publicity
    if self.public
      "public"
    else
      "private"
    end
  end

  def start_scenes
    self.scenes.where('endgame = false').map do |scene|
      [scene.title, scene.id]
    end
  end

  def is_valid?
    self.start_scene_id &&
    self.scenes.any? &&
    self.scenes.any? { |s| s.endgame }
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :account, dependent: :destroy
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  after_create :add_account

  def add_account
    Account.create(user_id: self.id)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
    @account = Account.find(params[:id])
    @private = @account.private_stories
    @public = @account.public_stories
    @invalid = @account.invalid_stories
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  def new
    @scene = Scene.find(params[:scene_id])
    @choice = @scene.choices.new
  end

  def create
    @scene = Scene.find(params[:scene_id])
    @choice = @scene.choices.new(choice_params)
    unless @choice.save
      # add choice errors partial
    end
  end

  def destroy
    respond_to :js
    @scene = Scene.find(params[:scene_id])
    choice = @scene.choices.find(params[:id])
    choice.destroy
  end

  private

  def choice_params
    params.require(:choice).permit(:text, :dest_scene_id)
  end
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  def new
    @story = Story.find(params[:story_id])
    @scene = @story.scenes.new
  end

  def create
    @story = Story.find(params[:story_id])
    @scene =  @story.scenes.new(scene_params)
    unless @scene.save
      render partial: 'scenes/edit_error', locals: {
        scene: @scene
      }
    end
  end

  def edit
    @story = Story.find(params[:story_id])
    @scene = @story.scenes.find(params[:id])
  end

  def update
    @scene  = Scene.find(params[:id])
    unless @scene.update(scene_params)
      render partial: "scenes/edit_error", locals: {
        scene: @scene
      }
    end
  end

  def destroy
    scene = Scene.find(params[:id])
    @story = scene.story
    @id = scene.id
    scene.destroy
  end

  def hide_edit_scene
  end

  def toggle_endgame
    @scene = Scene.find(params[:format])
    @scene.toggle_endgame
  end

  private
  def scene_params
    params.require(:scene).permit(:title, :text)
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @stories = Story.all_public
    @most_recent = Story.most_recent_public(3)
  end

  def show
    @story = Story.find(params[:id])
    @scene = @story.scenes.find(@story.start_scene_id) if @story.start_scene_id
    # @story.update_attribute :plays, @story.plays + 1
  end

  def make_choice
    @choice = Choice.find(params[:format])
    # @story = choice.scene.story
    @next_scene = Scene.find(@choice.dest_scene_id)
  end

  def new
    @account = current_user.account
    @story = @account.stories.new
  end

  def create
    @story = Story.new(story_params)
    if @story.save
      @story.update_attribute :account_id, current_user.account.id
      redirect_to account_path(current_user.account)
    else
      render :new
    end
  end

  def destroy
    story = Story.find(params[:id])
    @id = story.id
    story.destroy
    respond_to :js
  end

  def edit
    @story = Story.find(params[:id])
  end

  def update
    respond_to :js
    @story = Story.find(params[:id])
    if @story.update(story_params)
      render partial: 'stories/success_edit', locals: { story: @story }
    else
      render partial: 'stories/edit_error', locals: { story: @story }
    end
  end

  def show_details
    @story = Story.find(params[:format])
    render :show_details
  end

  def hide_details
    respond_to :js
    render :hide
  end

  def show_edit
    @story = Story.find(params[:format])
  end

  def toggle_publicity
    @story = Story.find(params[:format])
    @story.toggle_publicity
    @public = current_user.account.public_stories
    @private = current_user.account.private_stories
    # respond_to :js
  end

  def set_start_scene
    @scene = Scene.find(params[:start_scene_id])
    @story = @scene.story
    @previous = Scene.find(@story.start_scene_id) if @story.start_scene_id
    @story.update_attribute :start_scene_id, params[:start_scene_id]
  end

  private

  def story_params
    params.require(:story).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/show.html.erb
<h3>this is your account profile</h3>
<div id="edit-panel"></div>
<div class="story-block cfx">
  <h3>public stories</h3>
  <div id="public">
    <%= render partial: 'stories/edit_block', locals: { stories: @public } %>
  </div>
</div>

<div class="story-block cfx">
  <h3>private stories</h3>
  <div id="private">
    <%= render partial: 'stories/edit_block', locals: { stories: @private } %>
  </div>
</div>

<div class="story-block cfx">
  <h3>incomplete stories</h3>
  <div id="invalid">
    <%= render partial: 'stories/edit_block', locals: { stories: @invalid } %>
  </div>
</div>

app/views/choices/_form.html.erb
<%= form_for [scene, choice], remote: true do |f| %>
  <%= f.label :text %>
  <%= f.text_field :text %><br>
  <%= f.label "desination scene" %>
  <%= f.select(:dest_scene_id, options_for_select(scene.story.select_options))%>
  <%= f.submit "add choice" %>
<% end %>

app/views/choices/create.js.erb
// add choice to choice list in edit panel
// add re-render scene card
$("#scene-choices")
.empty()
.append("<%= j render partial: 'scenes/choice_list', locals: { scene: @scene }%>");
$("#scene-<%= @scene.id%>")
.after("<%= j render partial: 'scenes/card', locals: { scene: @scene }%>")
.remove();

app/views/choices/destroy.js.erb
$("#scene-choices")
.empty()
.append("<%= j render partial: 'scenes/choice_list', locals: { scene: @scene }%>");
$("#scene-<%= @scene.id%>")
.after("<%= j render partial: 'scenes/card', locals: { scene: @scene }%>")
.remove();

app/views/choices/new.js.erb
$("#choice-form").empty().append("<%= j render partial: 'choices/form', locals: { choice: @choice, scene: @scene }%>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ellis</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="sidebar">
      <h1><%= link_to "ellis", stories_path %></h1>
      <ul id="nav-links">
        <% if current_user && current_user.admin %>
          <li>admin</li>
          <li><%= link_to "new story", new_account_story_path(current_user.account)%></li>
          <li><%= link_to "account", account_path(current_user.account)%></li>
          <li><%= link_to "sign out", destroy_user_session_path, method: :delete %></li>
        <% elsif current_user %>
          <li><%= link_to "new story", new_account_story_path(current_user.account)%></li>
          <li><%= link_to "account", account_path(current_user.account)%></li>
          <li><%= link_to "sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "sign in", new_user_session_path %></li>
          <li><%= link_to "sign up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
    <div id="window">
      <%= yield %>
    </div>
  </body>
</html>

app/views/scenes/_add_scene.html.erb
<%= link_to "x", hide_edit_scene_path, id: 'close', remote: true%>
<h3>you have indicated that you would like to add a new scene</h3>
<div id="errors"></div>
<%= form_for [@story, @scene], remote: true do |f| %>
  <%= f.label :title%>
  <%= f.text_field :title %>
  <%= f.label :text%>
  <%= f.text_area :text, size: "30x10" %>
  <%= f.submit "save scene" %>
<% end %>

app/views/scenes/_card.html.erb
<%= link_to edit_story_scene_path(scene.story, scene), remote: true do %>
  <div class="scene" id="scene-<%=scene.id%>">
    <h3><%= scene.title %></h3>
    <p><%= scene.get_desc(140) %></p>

    <% if scene.endgame%>
      <p class="no-choices"><strong>ENDGAME</strong></p>
    <% elsif scene.story.start_scene_id == scene.id %>
      <p id="start-game"><strong>START</strong></p>
    <% end %>
    <% if scene.choices.any? %>
      <p><strong>choices:</strong></p>
    <% else %>
      <p><strong>no choices</strong></p>
    <% end %>

    <ul class="choices">
      <% scene.get_choices(3).each do |choice| %>
        <li><%= choice.text %></li>
      <% end %>
      <% if scene.choices.length > 3 %>
        <li><strong>more choices</strong></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/scenes/_choice_list.html.erb
<% scene.choices.each do |choice| %>
  <p>
    <strong><%= choice.text %></strong>
    scene: <%= Scene.title_by_id(choice.dest_scene_id) %>
    <%= link_to "delete", scene_choice_path(scene, choice), remote: true, method: :delete %>
  </p>
<% end %>

app/views/scenes/_edit_error.html.erb
<div id="error">
  <% scene.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
</div>

app/views/scenes/_edit_error.js.erb
$("#errors")
.empty()
.append("<%= j render partial: 'scenes/edit_error.html', locals: {scene: scene}%>")
.show();

app/views/scenes/_edit_panel.html.erb
<%= link_to "x", hide_edit_scene_path, id: 'close', remote: true%>
<h3 id="title">you are editing '<%= scene.title.downcase%>'</h3>
<div id="errors"></div>
<span id="delete"><%= link_to "delete", story_scene_path(scene.story, scene), method: :delete, remote: true %></span>

<%= form_for [scene.story, scene], remote: true do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :text %><br>
  <%= f.text_area :text, size: "60x10" %><br>
  <%= f.submit "save"%>
<% end %>
<p id="endgame">endgame status: <%= link_to scene.endgame.to_s, toggle_endgame_path(scene), remote: true%></p>
<%= link_to "add choice", new_scene_choice_path(scene), remote: true %>
<div id="choice-form"></div>
<div id="scene-choices">
  <%= render partial: "scenes/choice_list", locals: { scene: scene } %>
</div>

app/views/scenes/_status.html.erb
<p id="endgame">endgame status: <%= link_to scene.endgame.to_s, toggle_endgame_path(scene), remote: true%></p>

app/views/scenes/create.js.erb
$("#scenes-block")
.append("<%= j render partial: 'scenes/card', locals: { scene: @scene, story: @story }%>");
$("#edit-panel").empty().hide();
$("#start-select")
.empty()
.append("<%= j render partial: 'stories/start_scene_form', locals: { story: @story }%>");

app/views/scenes/destroy.js.erb
$("#scene-<%=@id%>").remove();
$("#edit-panel").empty().hide();
$("#start-select")
.empty()
.append("<%= j render partial: 'stories/start_scene_form', locals: { story: @story }%>");

app/views/scenes/edit.js.erb
$("#edit-panel")
.empty().show()
.append("<%= j render partial: 'scenes/edit_panel', locals: {scene: @scene}%>")

app/views/scenes/hide_edit_scene.js.erb
$("#edit-panel").empty().hide();

app/views/scenes/new.js.erb
$("#edit-panel")
.empty()
.show()
.append("<%= j render partial: 'add_scene', locals: {story: @story, scene: @scene }%>");

app/views/scenes/toggle_endgame.js.erb
$("#endgame")
.empty()
.append("<%= j render partial: 'scenes/status', locals: {scene: @scene} %>");
$("#scene-<%= @scene.id%>")
.after("<%= j render partial: 'scenes/card', locals: { scene: @scene }%>")
.remove();

app/views/scenes/update.js.erb
$("#errors").empty();
$("#title").text("you are editing '<%= @scene.title.downcase%>'")
$("#scene-<%= @scene.id%>")
.after("<%= j render partial: 'scenes/card', locals: { scene: @scene }%>")
.remove();

app/views/stories/_details.html.erb
<%= link_to "x", hide_details_path, id: 'close', remote: true%>
<h3><%= story.title%></h3>
<p>
  <%= story.description%>
</p>
<span class="metrics">views <%= story.plays %></span>
<%= link_to "start story", account_story_path(story.account, story) %>

app/views/stories/_edit.html.erb
<%= link_to "x", hide_edit_path, id: 'close', remote: true%>
<h3>you are editing '<%= story.title.downcase%>'</h3>
<div id="errors"></div>
<span class="metrics">
  visibility <span id="publicity"><%= link_to story.publicity, toggle_publicity_path(story), remote: true %></span>
  views <%= story.plays %>
</span>
<span id="delete"><%= link_to "delete", account_story_path(story.account, story), method: :delete, remote: true %></span>

<%= form_for [story.account, story], remote: true do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :description %><br>
  <%= f.text_area :description, size: "60x10" %><br>
  <%= f.submit "save"%>
<% end %>
<%= link_to "start story", account_story_path(story.account, story) %>

app/views/stories/_edit_block.html.erb
<% stories.each do |story| %>
  <%= link_to show_edit_path(story), remote: true do %>
    <%= render partial: "stories/card", locals: { data: story }%>
  <% end %>
<% end %>

app/views/stories/_edit_error.html.erb
<div id="error">
  <% story.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
</div>

app/views/stories/_edit_error.js.erb
$("#errors")
.empty()
.append("<%= j render partial: 'stories/edit_error.html', locals: {story: story}%>")
.show();

app/views/stories/_game.html.erb
<div id="text">
  <%= scene.text%>
</div>
<% if !scene.endgame%>
  <div id="choices">
    <ul>
    <% scene.choices.each do |choice| %>
      <li><%= link_to choice.text, make_choice_path(choice), remote: true %></li>
    <% end %>
  </ul>
  </div>
<% else %>
  <%= link_to account_story_path(scene.story.account, scene.story) do %>
    <h3>Game Over</h3>
  <% end %>
<% end %>

app/views/stories/_success_edit.js.erb
$("#errors").empty();
$("#edit-panel h3").text("you are editing '<%= story.title.downcase %>'")
$("#card-<%= story.id%>")
.after("<%= j render partial: 'stories/card', locals: { data: story }%>")
.remove();

app/views/stories/edit.html.erb
<h3>you are editing the scenes and choices in '<%= @story.title%>'</h3>
<div id="controls">
  <%= link_to "add scene", new_story_scene_path(@story), remote: true %>
  <div id="start-select">
    <%= render partial: 'stories/start_scene_form', locals: { story: @story }%>
  </div>
</div>

<div id="edit-panel"></div>

<div id="scenes-block">
  <% @story.scenes.each do |scene| %>
    <%= render partial: "scenes/card", locals: { scene: scene, story: @story }%>
  <% end %>
</div>

app/views/stories/hide.js.erb
$('#story-details').empty().hide();

app/views/stories/hide_edit.js.erb
$('#edit-panel').empty().hide();

app/views/stories/index.html.erb
<h3>this is the homepage</h3>
<div id="story-details">

</div>
  <div class="story-block cfx">
    <h3>most recent</h3>
    <% @most_recent.each do |story| %>
      <%= link_to show_details_path(story), remote: true do %>
        <%= render partial: "stories/card", locals: { data: story }%>
      <% end %>
    <% end %>
  </div>
  <div class="story-block cfx">
    <h3>all stories</h3>
    <% @stories.each do |story| %>
      <%= link_to show_details_path(story), remote: true do %>
        <%= render partial: "stories/card", locals: { data: story } %>
      <% end %>
    <% end %>
  </div>

app/views/stories/set_start_scene.js.erb
<% if @previous %>
  $("#scene-<%= @previous.id%>")
  .after("<%= j render partial: 'scenes/card', locals: { scene: @previous, story: @scene.story }%>")
  .remove();
<% end %>

$("#scene-<%= @story.start_scene_id%>")
.after("<%= j render partial: 'scenes/card', locals: { scene: @scene, story: @scene.story }%>")
.remove();

app/views/stories/show_edit.js.erb
$('#edit-panel')
  .empty()
  .css('background-color', $("#card-<%= @story.id %>").css('background-color'))
  .css('color', 'white')
  .append("<%= j render partial: 'stories/edit_details', locals: { story: @story }%>")
  .show()

app/views/stories/toggle_publicity.js.erb
$("#publicity").empty().append("<%= j link_to @story.publicity, toggle_publicity_path(@story), remote: true %>")
$("#public").empty().append("<%= j render partial: 'stories/edit_block', locals: { stories: @public } %>")
$("#private").empty().append("<%= j render partial: 'stories/edit_block', locals: { stories: @private } %>")